### ISSUE TITLE
Can't install on mac 

### ISSUE THREAD

**Issue by souvikhaldar** [faressoft/terminalizer#19]
When trying to install it throws permission error. Even when tried installing by becoming `root` then also getting error of the following form:-
`gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/.node-gyp/8.11.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/terminalizer/node_modules/node-pty-prebuilt/.node-gyp"`

**Comment by souvikhaldar** [comment]
Still getting the same error.

**Comment by faressoft** [comment]
Please execute and give me the results of

```
ls -l /usr/local/lib/node_modules/terminalizer
ls -ld /usr/local/lib/node_modules/terminalizer
ls -ld /usr/local/lib/node_modules
ls -ld /usr/local/bin
ls -ld /usr/local/share
```

**Comment by jukefr** [comment]
You could try this https://github.com/nodejs/node-gyp/issues/454#issuecomment-58792114
```
sudo npm install --unsafe-perm --verbose -g sails
```
When installing with `sudo`.

As for the reason an install currently won't work for you without a `sudo` is because it is trying to add global packages to `/usr/local/lib/...` and most operating systems will have permissions set to root for these folders.

If you are getting started with npm I would suggest you try and read this https://docs.npmjs.com/getting-started/fixing-npm-permissions (and the entire getting-started wiki for that matter) it talks about the `NPM_CONFIG_PREFIX` environment variable which allows you to set a custom global install path, preferably at your user's home folder (`~` or `/home/$USER`) this way you will not need sudo to install global packages.
