### ISSUE TITLE
Add zsh support 

### ISSUE THREAD

**Issue by plutov** [faressoft/terminalizer#2]
With zsh it works, but missing my config and gives a warning.

```
➜  ~ terminalizer record test
The recording session is started
Press CTRL+D to exit and save the recording
bash: /Users/pltvs/.bashrc: No such file or directory
Aliaksandrs-MacBook-Pro:~ pltvs$
```

**Comment by faressoft** [comment]
Hello @plutov,

> Summary: Zsh is already supported !

The default command is `bash -l` as mentioned in the `README`. 

The option `-l` is for
> Make bash act as if it had been invoked as a login shell

So the issue is not related to `zsh`. It is something about the missing file `.bashrc`.

Suggestions to your issue (Choose one of):
* Add the file `.bashrc`.
* You can record and then edit the generated recording YAML file and remove the waring message.
* You can record zsh instead by one of
  * Passing the option `-d` to the record command to change the default command.
  * Generate a config file `terminalizer config` then edit it and change the command then use it when you use the record command using the option `-c`.

![render1532508372860](https://user-images.githubusercontent.com/1908658/43189902-6c7db7ca-9000-11e8-8c16-c2d77ad4b701.gif)

Please try that and confirm :)

**Comment by plutov** [comment]
Confirming that it works.
