### ISSUE TITLE
Question: differences between termtosvg and asciinema?

### ISSUE THREAD

**Issue by trevordmiller** [faressoft/terminalizer#21]
I'm evaluating which terminal recorder to use and am not sure why to pick one over the other. Would you mind explaining why terminalizer was built when [termtosvg](https://github.com/nbedos/termtosvg) and [asciinema](https://github.com/asciinema/asciinema) are already available? Do they do the same thing, or are there different use cases? Thanks for the help :)

**Comment by faressoft** [comment]
@trevordmiller I built this tool for my own use after trying a lot of other similar tools to record terminals and generate animated GIF images. They weren't enough for me because of the lack of customizability.  

I need something that at the same time generates high quality images with small size and allows me to choose a custom font and colors, so from here I started. 

After that I decided to make a research about the available tools and built a new one that covers all the features in a single tool. A tool that generates GIF images (asciinema doesn't), generate a recording file that you can edit, generates a web player that you can use on your own website or even share the recording online like (asciinema).

The remarkable thing about this tool is that it is really high customizable and it is a cross platform tool (including Windows !). 

Please check:
[Features](https://github.com/faressoft/terminalizer#features)
[What's Next](https://github.com/faressoft/terminalizer#whats-next)

**Comment by AntonioRedondo** [comment]
Another advantage I think it's relevant is the fact Terminalizer is implemented in Node.js and not Python. Nothing wrong with Python. But if you're a front-end developer chances are that you'll prefer to deal with just one more npm package rather than installing Python stuff.

**Comment by Nakilon** [comment]
> the fact Terminalizer is implemented in Node.js and not Python

The most misleading thing I've read and felt for.

```none
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/unix/pty.cc:20:
npm ERR! In file included from ../../../nan/nan.h:56:
npm ERR! In file included from /Users/nakilon/Library/Caches/node-gyp/16.4.0/include/node/node.h:63:
npm ERR! In file included from /Users/nakilon/Library/Caches/node-gyp/16.4.0/include/node/v8.h:30:
npm ERR! /Users/nakilon/Library/Caches/node-gyp/16.4.0/include/node/v8-internal.h:454:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
```

As I understand terminalizer uses python during installation. So instead of depend only on python it depends both on python and npm.
